- name: RoboShop Project - Frontend
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: Copy Roboshop Configuration
      ansible.builtin.copy:
        src: /srv/myfiles/foo.conf
        dest: /etc/foo.conf

#  echo -e "\e[36m>>>>>>>>>>> Copy Roboshop Configuration <<<<<<<<<<<\e[0m"
#  cp nginx-roboshop.conf /etc/nginx/default.d/roboshop.conf  &>>${log}
#  func_exit_status
#
#  echo -e "\e[36m>>>>>>>>>>> Clean Old Content <<<<<<<<<<<\e[0m"
#  rm -rf /usr/share/nginx/html/*  &>>${log}
#  func_exit_status
#
#  echo -e "\e[36m>>>>>>>>>>> Download Application Content <<<<<<<<<<<\e[0m"
#  curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip  &>>${log}
#  func_exit_status
#
#  cd /usr/share/nginx/html
#
#
#  echo -e "\e[36m>>>>>>>>>>> Extract Application Content <<<<<<<<<<<\e[0m"
#  unzip /tmp/frontend.zip  &>>${log}
#  func_exit_status
#
#  echo -e "\e[36m>>>>>>>>>>> Start Nginx Service <<<<<<<<<<<\e[0m"
#  systemctl enable nginx  &>>${log}
#  systemctl restart nginx  &>>${log}
#  func_exit_status
#